/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/worker-configuration.d.ts` (hash: d8ad617ae6cf094cbf6e7ab900f31b7b)
interface __BaseEnv_Env {
  CMS_STATIC_SITE_BUCKET?: R2Bucket;
  ASSETS: Fetcher;
  PUBLIC_SITE_ENV: "staging" | "production" | "local";
  PUBLIC_SITE_PRIVATE_APP_BASE_URL?: string;
  CMS_STATIC_SITE_KEY_PREFIX: "sites";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("../dist/_worker.js/index");
  }
  interface StagingEnv {
    CMS_STATIC_SITE_BUCKET: R2Bucket;
    ASSETS: Fetcher;
    PUBLIC_SITE_ENV: "staging";
    PUBLIC_SITE_PRIVATE_APP_BASE_URL: string;
    CMS_STATIC_SITE_KEY_PREFIX: "sites";
  }
  interface ProductionEnv {
    CMS_STATIC_SITE_BUCKET: R2Bucket;
    ASSETS: Fetcher;
    PUBLIC_SITE_ENV: "production";
    PUBLIC_SITE_PRIVATE_APP_BASE_URL: string;
    CMS_STATIC_SITE_KEY_PREFIX: "sites";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "PUBLIC_SITE_ENV" | "CMS_STATIC_SITE_KEY_PREFIX">
    > {}
}
