import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
    "../packages/website-components/src/**/*.{ts,tsx}",
    "./node_modules/streamdown/dist/**/*.{js,mjs}",
  ],
  safelist: [
    "is-active",
    "is-open",
    "public-theme-navy-cream",
    "public-theme-timbermill-classic",
  ],
  theme: {
    extend: {
      borderRadius: {
        "cms-card": "var(--cms-radius-card)",
        "cms-control": "var(--cms-radius-control)",
        "cms-panel": "var(--cms-radius-panel)",
        "cms-pill": "var(--cms-radius-pill)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        cms: {
          accent: "var(--cms-accent)",
          "accent-subtle": "var(--cms-accent-subtle)",
          "accent-tint": "var(--cms-accent-tint)",
          border: "var(--cms-border)",
          "border-strong": "var(--cms-border-strong)",
          "border-subtle": "var(--cms-border-subtle)",
          canvas: "var(--cms-canvas)",
          error: "var(--cms-error)",
          "error-soft": "var(--cms-error-soft)",
          "error-strong": "var(--cms-error-strong)",
          "error-surface": "var(--cms-error-surface)",
          muted: "var(--cms-text-muted)",
          "on-accent": "var(--cms-text-on-accent)",
          "overlay-border": "var(--cms-overlay-border)",
          "overlay-text": "var(--cms-overlay-text)",
          raised: "var(--cms-surface-raised)",
          secondary: "var(--cms-text-secondary)",
          subtle: "var(--cms-text-subtle)",
          success: "var(--cms-success)",
          "success-strong": "var(--cms-success-strong)",
          "success-surface": "var(--cms-success-surface)",
          sunken: "var(--cms-surface-sunken)",
          surface: "var(--cms-surface)",
          text: "var(--cms-text)",
          warning: "var(--cms-warning)",
          "warning-strong": "var(--cms-warning-strong)",
          "warning-surface": "var(--cms-warning-surface)",
          "warning-text": "var(--cms-warning-text)",
        },
        claim: {
          surface: "#171412",
          "surface-text": "#fffaf2",
          accent: "#f4c16a",
          "accent-hover": "#ffd27d",
          "on-accent": "#171412",
          muted: "#d8c9be",
          "check-surface": "#18211d",
          check: "#d7ff61",
        },
        input: "var(--input)",
        ring: "var(--ring)",
      },
      boxShadow: {
        canvas: "0 18px 50px rgba(22, 31, 26, 0.08)",
      },
    },
  },
  plugins: [],
} satisfies Config;
